server:
  port: 8080

  error:
    include-stacktrace: never
    include-message: never

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              # - "http://localhost:5173"
              - "https://user-app-theta-seven.vercel.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      # server:
      # webflux:
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY, GATEWAY_TIMEOUT
            methods: GET

      routes:
        - id: users
          uri: lb://user-service
          # uri: https://user-service-lcps.onrender.com
          predicates:
            - Path=/auth/users/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}

        - id: auth
          uri: lb://auth-service
          # uri: https://auth-service-hjq7.onrender.com
          predicates:
            - Path=/auth/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: authServiceCircuit
                fallbackUri: forward:/fallback/auth

        - id: orders
          uri: lb://order-service
          # uri: https://order-service-nxx7.onrender.com
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=0
            - RemoveRequestHeader=Cookie

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public.pem

eureka:
  client:
    service-url:
      # defaultZone: http://localhost:8761/eureka/ # LOCAL
      defaultZone: ${URL_EUREKA:http://eureka-server:8761/eureka/}
  instance:
    # hostname: api-gateway # Nombre del servicio para Eureka
    prefer-ip-address: true # En Docker, es mejor usar la IP para evitar problemas de resolución de nombres

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{X-Correlation-Id}]"

# logging:
# level:
#   org.springframework.cloud.gateway: DEBUG
#   org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG
#   org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
#   reactor.netty.http.client: DEBUG
#   reactor.netty.http.server: DEBUG
